import Footer from "@/components/general/Footer";
import Navbar from "./_components/navbar/index";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "MugiChawn App",
  description: "Generated by MugiChawn app",
};

const BrowseLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
};

export default BrowseLayout;
